#
# Module manifest for module 'Script packaging'
#
# Generated by: MosaicMK Software
#
# Generated on: 08/14/2018
#

@{

    # Script module or binary module file associated with this manifest
    ModuleToProcess = @( '.\ScriptPackaging.psm1' )

    # This GUID is used to uniquely identify this module.
    GUID = '9241348a-e6f3-4fc3-82a0-f7e7b3690b12'

    # The author of this module.
    Author = 'MosaicMK Software'

    # The company or vendor for this module.
    CompanyName = 'MosaicMK Software'

    # The version of this module.
    ModuleVersion = '1.1.3.1'

    # A description of this module.
    Description = 'Tools used to package PowerShell script or script resorces'

    # The minimum version of PowerShell needed to use this module.
    PowerShellVersion = '4.0'

    # The CLR version required to use this module.
    CLRVersion = '4.0'

    # The type files (.ps1xml) loaded by this module.
    # TypesToProcess = ''

    # The format files (.ps1xml) loaded by this module.
    # FormatsToProcess = ''

    # A list of assemblies that must be loaded before this module can work.
    RequiredAssemblies = @()

    CmdletsToExport = '*'

    # Lists additional items like icons, etc. that the module will use.
    FileList = ''

    # Module specific private data can be passed via this member.
    PrivateData = ''
}
